vich_uploader:
    db_driver: orm
    metadata:
        type: attribute
    

    mappings:
       services:
           uri_prefix: /assets/upload/services
           upload_destination: '%kernel.project_dir%/public/assets/upload/services'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

           inject_on_load: false
           delete_on_update: true
           delete_on_remove: true

