vich_uploader:
    db_driver: orm
    metadata:
        type: attribute
    

    mappings:
       services:
           uri_prefix: /images/services
           upload_destination: '%kernel.project_dir%/public/images/services'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

           inject_on_load: false
           delete_on_update: false
           delete_on_remove: true
        
       ads:
           uri_prefix: /images/ads
           upload_destination: '%kernel.project_dir%/public/images/ads'
           namer: vich_uploader.namer_uniqid
           directory_namer:
                service: vich_uploader.namer_directory_property
                options: { property: 'slug', transliterate: true } # supposing that the object contains a "slug" property or a "getSlug" method


           inject_on_load: false
           delete_on_update: true
           delete_on_remove: true
