vich_uploader:
    db_driver: orm
    storage: flysystem

    mappings:
        services:
            uri_prefix: '%env(APP_UPLOAD_SERVICE_URI_PREFIX)%'
            upload_destination: default
            namer: 
                service: 'Vich\UploaderBundle\Naming\PropertyNamer'
                options: 
                    property: 'title'
            directory_namer:
                service: vich_uploader.namer_directory_property
                options: 
                    property: 'title'
                    transliterate: true
            inject_on_load: true
            delete_on_update: true
            delete_on_remove: false
        
        
        ads1:
            uri_prefix: /images/ads
            upload_destination: default
            namer:
                service: Vich\UploaderBundle\Naming\PropertyNamer
                options: 
                    property: 'imageRename1'
            directory_namer:
                service: vich_uploader.namer_directory_property
                options: 
                    property: 'unique_code'
                    transliterate: true
            inject_on_load: true
            delete_on_update: true
            delete_on_remove: false
        
        ads2:
            uri_prefix: /images/ads
            upload_destination: default
            namer:
                service: Vich\UploaderBundle\Naming\PropertyNamer
                options: 
                    property: 'imageRename2'
            directory_namer:
                service: vich_uploader.namer_directory_property
                options: 
                    property: 'unique_code'
                    transliterate: true
            inject_on_load: true
            delete_on_update: true
            delete_on_remove: false

        ads3:
            uri_prefix: /images/ads
            upload_destination: default
            namer:
                service: Vich\UploaderBundle\Naming\PropertyNamer
                options: 
                    property: 'imageRename3'
            directory_namer:
                service: vich_uploader.namer_directory_property
                options: 
                    property: 'unique_code'
                    transliterate: true
            inject_on_load: true
            delete_on_update: true
            delete_on_remove: false
