<?php

namespace App\DataFixtures;

use App\Entity\Ad;
use DateTime;
use Doctrine\Bundle\FixturesBundle\Fixture;
use Doctrine\Persistence\ObjectManager;
use Symfony\Component\HttpFoundation\File\UploadedFile;

class AdsFixtures extends Fixture
{
    public function load(ObjectManager $manager): void
    {
            $ad1 = new Ad();
            $ad1->setTitle('Mazda');
            $ad1->setBrand($this->getReference('Mazda'));
            $ad1->setRegistrationYear(new DateTime('12/12/2012'));
            $ad1->setKilometers('12000');
            $ad1->setPrice('18000');
            $ad1->setEnergy('Essence');
            $ad1->setGearcase('Automatique');
            $ad1->setColor('Rouge');
            $ad1->setPower(21);
            $ad1->setDoor('5');
            $ad1->setImageName1('');
            $ad1->setImageName2('');
            $ad1->setImageName3('');
            $ad1->setSize1(0);
            $ad1->setSize2(0);
            $ad1->setSize3(0);
            $ad1->setImageFile1(new UploadedFile('public/images/ads/Mazda/crosby-hinze-qzst3cCbn6E-unsplash.jpg','crosby-hinze-qzst3cCbn6E-unsplash.jpg','blob', UPLOAD_ERR_OK, true));
            $ad1->setImageFile2(new UploadedFile('public/images/ads/Mazda/praswin-prakashan-dGsf8Y0n2d0-unsplash.jpg','praswin-prakashan-dGsf8Y0n2d0-unsplash.jpg','blob', UPLOAD_ERR_OK, true));
            $ad1->setImageFile3(new UploadedFile('public/images/ads/Mazda/aron-yigin-d7R8GOLyC60-unsplash.jpg',
            'aron-yigin-d7R8GOLyC60-unsplash.jpg','blob', UPLOAD_ERR_OK, true));
            $ad1->setImageRename1('first-pic');
            $ad1->setImageRename2('second-pic');
            $ad1->setImageRename3('third-pic');
            $ad1->setAirConditioner(true);
            $ad1->setGps(true);
            $manager->persist($ad1);

            // $ad2 = new Ad();
            // $ad2->setTitle('Fiat500');
            // $ad2->setBrand($this->getReference('Fiat'));
            // $ad2->setRegistrationYear(new DateTime('12/12/2017'));
            // $ad2->setKilometers('28632');
            // $ad2->setPrice('7500');
            // $ad2->setEnergy('Essence');
            // $ad2->setGearcase('Manuelle');
            // $ad2->setColor('Rouge');
            // $ad2->setPower(8);
            // $ad2->setDoor('3');
            // $ad2->setImageName1('');
            // $ad2->setImageName2('');
            // $ad2->setImageName3('');
            // $ad2->setSize1(0);
            // $ad2->setSize2(0);
            // $ad2->setSize3(0);
            // $ad2->setImageFile1(new UploadedFile('public/images/ads/Fiat/giacomo-ghironi-2U-ebb4i_7Q-unsplash.jpg','ivan-jevtic-oZaPKFFqJ7s-unsplash.jpg','blob', UPLOAD_ERR_OK, true));
            // $ad2->setImageFile2(new UploadedFile('public/images/ads/Fiat/janko-ferlic-doli0TqGBac-unsplash.jpg',
            // 'praswin-prakashan-dGsf8Y0n2d0-unsplash.jpg','blob', UPLOAD_ERR_OK, true));
            // $ad2->setImageFile3(new UploadedFile('public/images/ads/Fiat/sean-whelan-VcVItFUI6g0-unsplash.jpg','obi-pixel8propix-S4M_m4QjY38-unsplash.jpg','blob', UPLOAD_ERR_OK, true));
            // $ad2->setImageRename1('first-pic');
            // $ad2->setImageRename2('second-pic');
            // $ad2->setImageRename3('thrid-pic');
            // $ad2->setAirConditioner(true);
            // $ad2->setAndroidAuto(true);
            // $manager->persist($ad2);

            // $ad3 = new Ad();
            // $ad3->setTitle('Mercedes');
            // $ad3->setBrand($this->getReference('Mercedes'));
            // $ad3->setRegistrationYear(new DateTime('03/21/2022'));
            // $ad3->setKilometers('8523');
            // $ad3->setPrice('32000');
            // $ad3->setEnergy('Diesel');
            // $ad3->setGearcase('Manuelle');
            // $ad3->setColor('Noire');
            // $ad3->setPower(35);
            // $ad3->setDoor('5');
            // $ad3->setImageName1('');
            // $ad3->setImageName2('');
            // $ad3->setImageName3('');
            // $ad3->setSize1(0);
            // $ad3->setSize2(0);
            // $ad3->setSize3(0);
            // $ad3->setImageFile1(new UploadedFile('public/images/ads/Mercedes/mark-tryapichnikov-MllJgoAFTcE-unsplash.jpg','ivan-jevtic-oZaPKFFqJ7s-unsplash.jpg','blob', UPLOAD_ERR_OK, true));
            // $ad3->setImageFile2(new UploadedFile('public/images/ads/Mercedes/leon-trilk-WP0WuLpQbEU-unsplash.jpg',
            // 'praswin-prakashan-dGsf8Y0n2d0-unsplash.jpg','blob', UPLOAD_ERR_OK, true));
            // $ad3->setImageFile3(new UploadedFile('public/images/ads/Mercedes/christian-wiediger-DnUbTwfOX0g-unsplash.jpg','obi-pixel8propix-S4M_m4QjY38-unsplash.jpg','blob', UPLOAD_ERR_OK, true));
            // $ad3->setImageRename1('first-pic');
            // $ad3->setImageRename2('second-pic');
            // $ad3->setImageRename3('thrid-pic');
            // $ad3->setAirConditioner(true);
            // $ad3->setSpeedRegulator(true);
            // $ad3->setGps(true);
            // $manager->persist($ad3);

            // $ad4 = new Ad();
            // $ad4->setTitle('Peugeot-206');
            // $ad4->setBrand($this->getReference('Peugeot'));
            // $ad4->setRegistrationYear(new DateTime('07/16/2011'));
            // $ad4->setKilometers('66230');
            // $ad4->setPrice('4900');
            // $ad4->setEnergy('Diesel');
            // $ad4->setGearcase('Manuelle');
            // $ad4->setColor('Noire');
            // $ad4->setPower(9);
            // $ad4->setDoor('5');
            // $ad4->setImageName1('');
            // $ad4->setImageName2('');
            // $ad4->setImageName3('');
            // $ad4->setSize1(0);
            // $ad4->setSize2(0);
            // $ad4->setSize3(0);
            // $ad4->setImageFile1(new UploadedFile('public/images/ads/Peugeot206/konrad-bednarek-4F1zFy3NvFI-unsplash.jpg','konrad-bednarek-4F1zFy3NvFI-unsplash.jpg','blob', UPLOAD_ERR_OK, true));
            // $ad4->setImageFile2(new UploadedFile('public/images/ads/Peugeot206/konrad-bednarek-T8JAC7y8HqU-unsplash.jpg',
            // 'konrad-bednarek-T8JAC7y8HqU-unsplash.jpg','blob', UPLOAD_ERR_OK, true));
            // $ad4->setImageFile3(new UploadedFile('public/images/ads/Peugeot206/alvaro-reyes-Ar87_RWv7Mo-unsplash.jpg','alvaro-reyes-Ar87_RWv7Mo-unsplash.jpg','blob', UPLOAD_ERR_OK, true));
            // $ad4->setImageRename1('first-pic');
            // $ad4->setImageRename2('second-pic');
            // $ad4->setImageRename3('thrid-pic');
            // $ad4->setAirConditioner(true);
            // $manager->persist($ad4);
            

            // $ad5 = new Ad();
            // $ad5->setTitle('Porsche');
            // $ad5->setBrand($this->getReference('Porsche'));
            // $ad5->setRegistrationYear(new DateTime('09/10/2020'));
            // $ad5->setKilometers('23651');
            // $ad5->setPrice('39500');
            // $ad5->setEnergy('Essence');
            // $ad5->setGearcase('Automatique');
            // $ad5->setColor('Blanche');
            // $ad5->setPower(53);
            // $ad5->setDoor('3');
            // $ad5->setImageName1('');
            // $ad5->setImageName2('');
            // $ad5->setImageName3('');
            // $ad5->setSize1(0);
            // $ad5->setSize2(0);
            // $ad5->setSize3(0);
            // $ad5->setImageFile1(new UploadedFile('public/images/ads/Porsche/or-hakim-0qcexMtNjR4-unsplash.jpg','ivan-jevtic-oZaPKFFqJ7s-unsplash.jpg','blob', UPLOAD_ERR_OK, true));
            // $ad5->setImageFile2(new UploadedFile('public/images/ads/Porsche/or-hakim-dooqgB_U7UU-unsplash.jpg',
            // 'praswin-prakashan-dGsf8Y0n2d0-unsplash.jpg','blob', UPLOAD_ERR_OK, true));
            // $ad5->setImageFile3(new UploadedFile('public/images/ads/Porsche/redcharlie-mugDbuNnbd0-unsplash.jpg','obi-pixel8propix-S4M_m4QjY38-unsplash.jpg','blob', UPLOAD_ERR_OK, true));
            // $ad5->setImageRename1('first-pic');
            // $ad5->setImageRename2('second-pic');
            // $ad5->setImageRename3('thrid-pic');
            // $ad5->setAirConditioner(true);
            // $ad5->setSpeedRegulator(true);
            // $ad5->setAndroidAuto(true);
            // $ad5->setGps(true);
            // $manager->persist($ad5);

            // $ad6 = new Ad();
            // $ad6->setTitle('Renault');
            // $ad6->setBrand($this->getReference('Renault'));
            // $ad6->getId('6');
            // $ad6->setRegistrationYear(new DateTime('07/10/2021'));
            // $ad6->setKilometers('21520');
            // $ad6->setPrice('7500');
            // $ad6->setEnergy('Essence');
            // $ad6->setGearcase('Automatique');
            // $ad6->setColor('Jaune');
            // $ad6->setPower(16);
            // $ad6->setDoor('5');
            // $ad6->setImageName1('');
            // $ad6->setImageName2('');
            // $ad6->setImageName3('');
            // $ad6->setSize1(0);
            // $ad6->setSize2(0);
            // $ad6->setSize3(0);
            // $ad6->setImageFile1(new UploadedFile('public/images/ads/Renault/martin-katler-hb8fkAWx9gc-unsplash.jpg','ivan-jevtic-oZaPKFFqJ7s-unsplash.jpg','blob', UPLOAD_ERR_OK, true));
            // $ad6->setImageFile2(new UploadedFile('public/images/ads/Renault/peter-varga-P1atr7HJ8Zs-unsplash.jpg',
            // 'praswin-prakashan-dGsf8Y0n2d0-unsplash.jpg','blob', UPLOAD_ERR_OK, true));
            // $ad6->setImageFile3(new UploadedFile('public/images/ads/Renault/rafal-jedrzejek-pK2EOfJUZmU-unsplash.jpg','obi-pixel8propix-S4M_m4QjY38-unsplash.jpg','blob', UPLOAD_ERR_OK, true));
            // $ad6->setImageRename1('first-pic');
            // $ad6->setImageRename2('second-pic');
            // $ad6->setImageRename3('thrid-pic');
            // $ad6->setAirConditioner(true);
            // $ad6->setReversingCamera(true);
            // $ad6->setGps(true);
            // $manager->persist($ad6);

            // $ad7 = new Ad();
            // $ad7->setTitle('Tesla');
            // $ad7->setBrand($this->getReference('Tesla'));
            // $ad7->setRegistrationYear(new DateTime('04/02/2022'));
            // $ad7->setKilometers('17520');
            // $ad7->setPrice('13000');
            // $ad7->setEnergy('Electrique');
            // $ad7->setGearcase('Automatique');
            // $ad7->setColor('Noire');
            // $ad7->setPower(25);
            // $ad7->setDoor('5');
            // $ad7->setImageName1('');
            // $ad7->setImageName2('');
            // $ad7->setImageName3('');
            // $ad7->setSize1(0);
            // $ad7->setSize2(0);
            // $ad7->setSize3(0);
            // $ad7->setImageFile1(new UploadedFile('public/images/ads/Tesla/bram-van-oost-eaPkue76Ip4-unsplash.jpg','ivan-jevtic-oZaPKFFqJ7s-unsplash.jpg','blob', UPLOAD_ERR_OK, true));
            // $ad7->setImageFile2(new UploadedFile('public/images/ads/Tesla/jp-valery-_s5aRlUXtyg-unsplash.jpg',
            // 'praswin-prakashan-dGsf8Y0n2d0-unsplash.jpg','blob', UPLOAD_ERR_OK, true));
            // $ad7->setImageFile3(new UploadedFile('public/images/ads/Tesla/stefan-lehner-jQSNiYd6oUM-unsplash.jpg','obi-pixel8propix-S4M_m4QjY38-unsplash.jpg','blob', UPLOAD_ERR_OK, true));
            // $ad7->setImageRename1('first-pic');
            // $ad7->setImageRename2('second-pic');
            // $ad7->setImageRename3('thrid-pic');
            // $ad7->setAirConditioner(true);
            // $ad7->setSpeedRegulator(true);
            // $ad7->setReversingCamera(true);
            // $ad7->setGps(true);
            // $manager->persist($ad7);

            // $ad8 = new Ad();
            // $ad8->setTitle('Renault-Clio');
            // $ad8->setBrand($this->getReference('Renault'));
            // $ad8->setRegistrationYear(new DateTime('04/04/2019'));
            // $ad8->setKilometers('12456');
            // $ad8->setPrice('4200');
            // $ad8->setEnergy('Essence');
            // $ad8->setGearcase('Manuelle');
            // $ad8->setColor('Noire');
            // $ad8->setPower(10);
            // $ad8->setDoor('5');
            // $ad8->setImageName1('');
            // $ad8->setImageName2('');
            // $ad8->setImageName3('');
            // $ad8->setSize1(0);
            // $ad8->setSize2(0);
            // $ad8->setSize3(0);
            // $ad8->setImageFile1(new UploadedFile('public/images/ads/Renault Clio/samy-mounichy-AZcfIq5X-W8-unsplash.jpg','samy-mounichy-AZcfIq5X-W8-unsplash.jpg','blob', UPLOAD_ERR_OK, true));
            // $ad8->setImageFile2(new UploadedFile('public/images/ads/Renault Clio/samy-mounichy-eTuO9BNtcPA-unsplash.jpg',
            // 'samy-mounichy-eTuO9BNtcPA-unsplash.jpg','blob', UPLOAD_ERR_OK, true));
            // $ad8->setImageFile3(new UploadedFile('public/images/ads/Renault Clio/samy-mounichy-ZRuo9qFprXk-unsplash.jpg','samy-mounichy-ZRuo9qFprXk-unsplash.jpg','blob', UPLOAD_ERR_OK, true));
            // $ad8->setImageRename1('first-pic');
            // $ad8->setImageRename2('second-pic');
            // $ad8->setImageRename3('thrid-pic');
            // $ad8->setAirConditioner(true);
            // $ad8->setGps(true);
            // $manager->persist($ad8);

            
            // $ad9 = new Ad();
            // $ad9->setTitle('Mazda-CX3');
            // $ad9->setBrand($this->getReference('Mazda'));
            // $ad9->setRegistrationYear(new DateTime('02/18/2023'));
            // $ad9->setKilometers('35048');
            // $ad9->setPrice('39500');
            // $ad9->setEnergy('Diesel');
            // $ad9->setGearcase('Automatique');
            // $ad9->setColor('Grise');
            // $ad9->setPower(22);
            // $ad9->setDoor('5');
            // $ad9->setImageName1('');
            // $ad9->setImageName2('');
            // $ad9->setImageName3('');
            // $ad9->setSize1(0);
            // $ad9->setSize2(0);
            // $ad9->setSize3(0);
            // $ad9->setImageFile1(new UploadedFile('public/images/ads/Mazda CX3/austin-lowman-SpSVyLVB_5g-unsplash.jpg','austin-lowman-SpSVyLVB_5g-unsplash.jpg','blob', UPLOAD_ERR_OK, true));
            // $ad9->setImageFile2(new UploadedFile('public/images/ads/Mazda CX3/kelly-sikkema-XXherw1ujoI-unsplash.jpg',
            // 'kelly-sikkema-XXherw1ujoI-unsplash.jpg','blob', UPLOAD_ERR_OK, true));
            // $ad9->setImageFile3(new UploadedFile('public/images/ads/Mazda CX3/miles-loewen-2vyEZ7kiq4E-unsplash.jpg','miles-loewen-2vyEZ7kiq4E-unsplash.jpg','blob', UPLOAD_ERR_OK, true));
            // $ad9->setImageRename1('first-pic');
            // $ad9->setImageRename2('second-pic');
            // $ad9->setImageRename3('thrid-pic');
            // $ad9->setAirConditioner(true);
            // $ad9->setSpeedRegulator(true);
            // $ad9->setReversingCamera(true);
            // $ad9->setGps(true);
            // $manager->persist($ad9);

            // $ad10 = new Ad();
            // $ad10->setTitle('Mercedes-Benz');
            // $ad10->setBrand($this->getReference('Mercedes'));
            // $ad10->setRegistrationYear(new DateTime('04/08/2019'));
            // $ad10->setKilometers('85630');
            // $ad10->setPrice('31800');
            // $ad10->setEnergy('Diesel');
            // $ad10->setGearcase('Manuelle');
            // $ad10->setColor('Noire');
            // $ad10->setPower(29);
            // $ad10->setDoor('5');
            // $ad10->setImageName1('');
            // $ad10->setImageName2('');
            // $ad10->setImageName3('');
            // $ad10->setSize1(0);
            // $ad10->setSize2(0);
            // $ad10->setSize3(0);
            // $ad10->setImageFile1(new UploadedFile('public/images/ads/Mercedes Benz/dekler-ph-ZmcOEbW3hDg-unsplash.jpg','dekler-ph-ZmcOEbW3hDg-unsplash.jpg','blob', UPLOAD_ERR_OK, true));
            // $ad10->setImageFile2(new UploadedFile('public/images/ads/Mercedes Benz/mikolaj-gorzynski-341Jd6-foKo-unsplash.jpg',
            // 'mikolaj-gorzynski-341Jd6-foKo-unsplash.jpg','blob', UPLOAD_ERR_OK, true));
            // $ad10->setImageFile3(new UploadedFile('public/images/ads/Mercedes Benz/nigel-tadyanehondo-cuyqetla_Q-unsplash.jpg','nigel-tadyanehondo-cuyqetla_Q-unsplash.jpg','blob', UPLOAD_ERR_OK, true));
            // $ad10->setImageRename1('first-pic');
            // $ad10->setImageRename2('second-pic');
            // $ad10->setImageRename3('thrid-pic');
            // $ad10->setAirConditioner(true);
            // $ad10->setSpeedRegulator(true);
            // $ad10->setReversingCamera(true);
            // $manager->persist($ad10);

            // $ad11 = new Ad();
            // $ad11->setTitle('Fiat-Panda');
            // $ad11->setBrand($this->getReference('Fiat'));
            // $ad11->setRegistrationYear(new DateTime('11/04/2008'));
            // $ad11->setKilometers('86245');
            // $ad11->setPrice('6800');
            // $ad11->setEnergy('Essence');
            // $ad11->setGearcase('Automatique');
            // $ad11->setColor('Blanche');
            // $ad11->setPower(12);
            // $ad11->setDoor('5');
            // $ad11->setImageName1('');
            // $ad11->setImageName2('');
            // $ad11->setImageName3('');
            // $ad11->setSize1(0);
            // $ad11->setSize2(0);
            // $ad11->setSize3(0);
            // $ad11->setImageFile1(new UploadedFile('public/images/ads/Fiat panda/chris-brownless-Y4RAQ9oM4c0-unsplash.jpg','chris-brownless-Y4RAQ9oM4c0-unsplash.jpg','blob', UPLOAD_ERR_OK, true));
            // $ad11->setImageFile2(new UploadedFile('public/images/ads/Fiat panda/share-now-6FaTx3qMc5Q-unsplash.jpg',
            // 'share-now-6FaTx3qMc5Q-unsplash.jpg','blob', UPLOAD_ERR_OK, true));
            // $ad11->setImageFile3(new UploadedFile('public/images/ads/Fiat panda/share-now-V8Axzxhts5M-unsplash.jpg','share-now-V8Axzxhts5M-unsplash.jpg','blob', UPLOAD_ERR_OK, true));
            // $ad11->setImageRename1('first-pic');
            // $ad11->setImageRename2('second-pic');
            // $ad11->setImageRename3('thrid-pic');
            // $ad11->setAirConditioner(true);
            // $ad11->setSpeedRegulator(true);
            // $manager->persist($ad11);
        
            // $ad12 = new Ad();
            // $ad12->setTitle('Renault-Scenic');
            // $ad12->setBrand($this->getReference('Renault'));
            // $ad12->setRegistrationYear(new DateTime('01/02/2001'));
            // $ad12->setKilometers('99543');
            // $ad12->setPrice('6200');
            // $ad12->setEnergy('Essence');
            // $ad12->setGearcase('Manuelle');
            // $ad12->setColor('Rouge');
            // $ad12->setPower(8);
            // $ad12->setDoor('5');
            // $ad12->setImageName1('');
            // $ad12->setImageName2('');
            // $ad12->setImageName3('');
            // $ad12->setSize1(0);
            // $ad12->setSize2(0);
            // $ad12->setSize3(0);
            // $ad12->setImageFile1(new UploadedFile('public/images/ads/Renault Scenic/benjamin-nijs-g4XGoPHHGLY-unsplash.jpg','benjamin-nijs-g4XGoPHHGLY-unsplash.jpg','blob', UPLOAD_ERR_OK, true));
            // $ad12->setImageFile2(new UploadedFile('public/images/ads/Renault Scenic/vitali-adutskevich-cj8_O20Cz_0-unsplash.jpg',
            // 'vitali-adutskevich-cj8_O20Cz_0-unsplash.jpg','blob', UPLOAD_ERR_OK, true));
            // $ad12->setImageFile3(new UploadedFile('public/images/ads/Renault Scenic/vitali-adutskevich-f-Ob1ubCiIE-unsplash.jpg','vitali-adutskevich-f-Ob1ubCiIE-unsplash.jpg','blob', UPLOAD_ERR_OK, true));
            // $ad12->setImageRename1('first-pic');
            // $ad12->setImageRename2('second-pic');
            // $ad12->setImageRename3('thrid-pic');
            // $ad12->setAirConditioner(true);
            // $manager->persist($ad12);

            // $ad13 = new Ad();
            // $ad13->setTitle('Renault Captur');
            // $ad13->setBrand($this->getReference('Renault'));
            // $ad13->setRegistrationYear(new DateTime('12/12/2012'));
            // $ad13->setKilometers('15264');
            // $ad13->setPrice('11870');
            // $ad13->setEnergy('Essence');
            // $ad13->setGearcase('Manuelle');
            // $ad13->setColor('Blanche');
            // $ad13->setPower(25);
            // $ad13->setDoor('5');
            // $ad13->setImageName1('');
            // $ad13->setImageName2('');
            // $ad13->setImageName3('');
            // $ad13->setSize1(0);
            // $ad13->setSize2(0);
            // $ad13->setSize3(0);
            // $ad13->setImageFile1(new UploadedFile('public/images/ads/Captur/vaclav-pechar-2aqHPRYXBRA-unsplash.jpg','vaclav-pechar-2aqHPRYXBRA-unsplash.jpg','blob', UPLOAD_ERR_OK, true));
            // $ad13->setImageFile2(new UploadedFile('public/images/ads/Captur/vaclav-pechar-E-S53sw_q3c-unsplash.jpg',
            // 'vaclav-pechar-E-S53sw_q3c-unsplash.jpg','blob', UPLOAD_ERR_OK, true));
            // $ad13->setImageFile3(new UploadedFile('public/images/ads/Captur/vaclav-pechar-FQuXuNWZdEs-unsplash.jpg','vaclav-pechar-FQuXuNWZdEs-unsplash.jpg','blob', UPLOAD_ERR_OK, true));
            // $ad13->setImageRename1('first-pic');
            // $ad13->setImageRename2('second-pic');
            // $ad13->setImageRename3('thrid-pic');
            // $ad13->setAirConditioner(true);
            // $ad13->setSpeedRegulator(true);
            // $ad13->setReversingCamera(true);
            // $ad13->setGps(true);
            // $manager->persist($ad13);

            $manager->flush();
        }
}
